const mongoose = require('mongoose')

//_id is auto generated by mongoose
const monthsSchema = new mongoose.Schema({
    monthCode : {
        type: String,
        maxlength: 3
    },
    monthDesc : {
        type: String,
    }
    //collection tag makes collection in DB names 'user'
    //timestamps tag adds createdAt and updatedAt fields to schema
}, { collection: 'months'})



module.exports = mongoose.model('Months', monthsSchema)