const mongoose = require('mongoose')

//_id is auto generated by mongoose
const resumeInfoSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        ref: 'User'
    },
    siteTitle: {
        type: String,
        required: true,
        unique: true
    },
    address: {
        type: String,
    },
    phone1Type: {
        type: String
    },
    phone2Type: {
        type: String
    },
    phone1: {
        type: String,
        match: /^[1-9]\d{2}-\d{3}-\d{4}/, // regex to work for format 123-456-7890
    },
    phone2: {
        type: String,
        match: /^[1-9]\d{2}-\d{3}-\d{4}/,
    },
    link1: {
        type: String
    },
    link2: {
        type: String
    },
    email1: {
        type: String
    },
    email2: {
        type: String
    },
    profSum: {
        type: String
    },
    theme: {
        type: String
    },
    skills: { //skills will be a comma separated list that will parsed on the webpage to be a list
        type: String
    }
}, { collection: 'resumeInfo', timestamps: true})


module.exports = mongoose.model('ResumeInfo', resumeInfoSchema)