const mongoose = require('mongoose')

//_id is auto generated by mongoose
const userInfoSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        ref: 'User'
    },
    siteTitle: {
        type: String,
        required: true,
        unique: true
    },
    address: {
        type: String,
    },
    phone1: {
        type: String,
        maxlength: 20 //room to add text other than numbers [i.e '+' '-' '(' ')' ]
    },
    phone2: {
        type: String,
        maxlength: 20
    },
    link1: {
        type: String
    },
    link2: {
        type: String
    },
    email1: {
        type: String
    },
    email2: {
        type: String
    }
}, { collection: 'userInfo', timestamps: true})


module.exports = mongoose.model('userInfo', userInfoSchema)