const mongoose = require('mongoose')

//_id is auto generated by mongoose
const statesSchema = new mongoose.Schema({
    stateCode : {
        type: String,
        maxlength: 2
    },
    stateDesc : {
        type: String,
    }
    //collection tag makes collection in DB names 'user'
    //timestamps tag adds createdAt and updatedAt fields to schema
}, { collection: 'states'})



module.exports = mongoose.model('States', statesSchema)