const mongoose = require('mongoose')
const bcrypt = require('bcryptjs')

//_id is auto generated by mongoose
const userSchema = new mongoose.Schema({
    firstName: {
        type: String,
        required: true
    },
    lastName: {
        type: String,
        required: true
    },
    username: {
        type: String,
        required: true,
        unique: true
    },
    password: {
        type: String,
        required: true
    } //collection tag makes collection in DB names 'user'
    //timestamps tag adds createdAt and updatedAt fields to schema
}, { collection: 'user', timestamps: true})

/*
    The following functions were taken from a website detailing how to has
    a password and check that password when someone is loging in. For more
    information on how to implement the second method and find out if the
    password inputted by the user is the one in the database

    https://coderrocketfuel.com/article/store-passwords-in-mongodb-with-node-js-mongoose-and-bcrypt
*/

//function that hashes the password before being saved to the database collection
userSchema.pre("save", function (next) {
    const user = this

    if(this.isModified("password") || this.isNew){
        bcrypt.genSalt(10, function (saltError, salt) {
            if(saltError) {
                return next(saltError)
            } else {
                bcrypt.hash(user.password, salt, function(hashError, hash) {
                    if (hashError) {
                      return next(hashError)
                    }
          
                    user.password = hash
                    next()
                })
            }
        })
    } else {
        return next()
    }
})

//method to compare passwords submitted by user in login page to verify user
userSchema.methods.comparePassword = function(password, callback) {
    bcrypt.compare(password, this.password, function(error, isMatch) {
        if(error) {
            return callback(error)
        } else {
            callback(null, isMatch);
        }
    })
}

module.exports = mongoose.model('User', userSchema)